import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { configureSelfHostedZXing, ZXING_WASM_PUBLIC_PATH } from "./zxing-config";

/**
 * Self-hosted WASM guarantees (docs/TECHNICAL_DESIGN.md §9.3). The public
 * binary is generated by scripts/sync-zxing-wasm.mjs, which runs via the
 * `pretest` hook — so these assertions verify the mechanism end to end:
 * the file exists, is byte-identical to the INSTALLED zxing-wasm decoder,
 * and the runtime override points exactly at it.
 */

const root = process.cwd();

function sha256(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

describe("self-hosted ZXing WASM", () => {
  it("the public binary exists and matches the installed zxing-wasm version byte-for-byte", () => {
    const publicWasm = join(root, "public", "wasm", "zxing_reader.wasm");
    const installedWasm = join(
      root,
      "node_modules",
      "zxing-wasm",
      "dist",
      "reader",
      "zxing_reader.wasm",
    );
    expect(sha256(publicWasm)).toBe(sha256(installedWasm));
  });

  it("the runtime override points at the public path the sync script writes", () => {
    expect(ZXING_WASM_PUBLIC_PATH).toBe("/wasm/zxing_reader.wasm");
  });

  it("registering the override never throws (safe before any decode)", () => {
    expect(() => configureSelfHostedZXing()).not.toThrow();
  });
});
